#image source
FROM python

#Listes des dépendances
COPY requirements.txt requirements.txt

#Installation des dépendances
RUN pip install -r requirements.txt

#Copie de mon application
COPY app_flask.py app_flask.py

#ouvrir le port flask
EXPOSE 9001

#démarrer mon application
CMD [ "python", "app_flask.py" ]

#excution de l'image : docker build -t my_app .
#construction d'une image à partir du dockerfile 
#démarrer un conteneur : docker run  -dit --name testappflask -p 9001:9001 monappflask