FROM python:3.9

#répertoire de travail
WORKDIR /app

#Listes des dépendances
COPY requirements.txt .

#Installation des dépendances
RUN pip install --no-cache-dir -r requirements.txt

#Copie de mon application
COPY . .

#ouvrir le port flask
EXPOSE 5000

CMD [ "python", "app_flask.py" ]

#excution de l'image : docker buil -t my_app .