version: '3.8' 

# liste des servicedifférents conteneurs
services:
  # mon premier conteneur mongodb
  mymongodb:
   #image du conteneur
    image: mongo
    restart: always 
    ports:
      - 27017:27017
    volumes:
     - "./data/db:/data/db"
     #Deploiement d'un réseau
    networks: 
      - app-mongo-VNet
    
    # conteneur de mon ui pour mongodb
  mongoui:
    #image de mon conteneur
    image: mongo-express
    restart : always
    #ports du conteneur 
    ports:
      - 8081:8081
    environment:
      # renseigne le nom du service contenant la bdd
      ME_CONFIG_MONGODB_SERVER: mymongodb
    depends_on: 
      - mymongodb
    networks:
      - app-mongo-VNet
  
  #conteneur de mon applicatio flask
  monapp:
    # construire à la volée mon image 
    build: .
    #ouverture des ports du conteneur de mon application flask
    ports:
      - 9002:9001
    networks:
     - app-mongo-VNet
    depends_on:
      - mymongodb
    #ajout d'une variable epour récupérer l'IP du conteneur Mongodb
    environment:
      - MONGO_HOST=mongodb


#fabrique mon réseau
networks:
  app-mongo-VNet:
    driver: bridge 
 
 #démarrer le docker compose : docker compose up
