version: '3.8' 

# liste des services
services:
  # mon premier service
  app_flask:
    image: my_app
    ports:
      - 5000:5000
    depends_on: 
      - mymongodb


  # seconde service
  mymongodb:
    image: mongo
    ports:
      - 27017:27017